baseTiles = {//redo entirely and in order
    "grass":[0,0],//plain, green grass
    "grass2":[160,608],
    "snow":[208,528],//
    "tree":[16,0],//
    "oak":[128,1104],//
    "deadtree":[48,464],//
    "snowtree":[176,544],//
    "rock":[176,0],//
    "water":[0,48],//
    "flower1":[16,48],//
    "flower2":[64,48],//
    "flower3":[112,48],//
    "mushroom":[80,256],//
    //paths
    "pathHORIZ":[0,544],//
    "pathVERT":[16,544],//
    "pathTDWN":[32,544],//
    "pathTUP":[48,544],//
    "pathTRT":[64,544],//
    "pathTLT":[80,544],//
    "pathCRS":[96,544],//
    "pathCRV1":[112,544],//
    "pathCRV2":[128,544],//
    "pathCRV3":[144,544],//
    "pathCRV4":[160,544],//
    //stuff
    "grave":[32,160],//
    "stoneblock":[288,0],//
    "woodblock":[112,0],//
    "stump1":[192,448],
    "stump2":[64,1120],
    "stump3":[80,1120],
    "campfire":[32,384],//
    "rain":[144,432],//
    "fenceV":[0,160],
    "fenceH":[16,160],
    "sand":[16,64],
    "boulder":[144,1232],
    "rockpile":[304,1072],
    "mapsign":[16,176],
    "bed":[128,112],
    "cactus":[160,48],
    "ankh":[128,96],
    "chest":[32,128],
    "woodplate":[112,80],
    "stoneplate":[128,80],
    "door":[288,96],
    "door2":[192,816],
    "door3":[32,848],
    "skull":[304,1024],
    "table":[64,352],
    "chair":[80,352],
    "sign":[80,512],
    "deskHORIZ":[112,128],
    "deskVERT":[0,144],
    "deskCRV1":[16,144],
    "deskCRV2":[32,144],
    "deskCRV3":[96,1264],
    "deskCRV4":[112,1264],
    "redX":[288,751],//this one was weird
    "redDownArrow":[96,640],
    "glasspane1":[160,560],
    "cloud":[240,736],
    "axeR":[0,192],
    "axeL":[272,192],
    "axeItem":[64,64],
    "statDisp":[80, 624],
    "log":[96, 0],
    "splitlog":[96,1120],
    "upArrow":[80,975],
    "downArrow":[96, 975],
    "hpIcon":[160,832],
    "string":[80,240],//probably another object like logs where no actual object (like Axe), just inv obj and sprite obj
    "fPoleR":[0,496],
    "fPoleL":[16,495],
    "fPole":[288,480],
    "ironsword":[272,16],
    "ironswordL":[192,192],
    "ironswordR":[80,192],
    "craftTable":[192,528],//just this for now as a click point
    "lootbag":[192,240],
    "abyss":[160,384],
    "void":[240,1232],//just blank space for event tiles (like map exit or dungeon stairs)
    "dungeonStairs":[0,352],
    "fish":[256, 480],
    "portalfish":[224,480],
    "cookedfish":[272, 480],
    "bobber":[304,480],
    "chest2":[240,816],
    "web":[208,400],
    "raft":[128,1264],
    "sail":[144,1264],//draw raft > player > sail
    "key":[16, 848],
    "coin":[176,240],
    "craftingtable":[192,528],
    "scroll":[160, 1264],
    "apple":[304,160],
    "trashcan":[128,752],
    //letters here
    "F":[80,768],
    "C":[32,768],
    //end letters
    "hitOutlineLeft":[112,176],
    "hitOutlineRight":[62,176],
    "hide":[224,272],
    "tunafish":[240,480],
    "cookedtuna":[64,496],
    "leatherArmorL":[159,272],
    "leatherArmorR":[209,272],
    "leatherArmorI":[288,224],
    "brasskey":[176,1264],
    "heart":[144,528],
    "speedbootsI":[144,448],
    "speedbootsR":[160,448],//might have to switch/tweak R/L or offset
    "speedbootsL":[160,432],
    "UPARROW":[208,1264],
    "DOWNARROW":[192,1264],
    "palmtree":[224,1264],
    "longbow":[32,240],
    "longbowL":[144,240],
    "longbowR":[128,240],
    "knife":[288,432],
    "knifeL":[304,464],
    "knifeR":[304,432],
    "spikein":[0,864],
    "spikeout":[0,848],
    "stairsR":[32,352],
    //projectiles -- all these have up down left right, bit bulky but makes easier in Projectile fxn
    "arrowup":[208,240],
    "arrowdown":[224,240],
    "arrowleft":[240,240],
    "arrowright":[256,240],
    "arrow":[48,1216],
    "pebble":[208,576],
    "whitewave":[144,736],
    "fireballup":[96,256],
    "fireballdown":[112,256],
    "fireballleft":[128,256],
    "fireballright":[144,256]
  }

  npcTiles = {
    "skelR":[128,16],
    "skelL":[128,32],
    "ghostR":[48,80],//ghost facing right coords
    "ghostL":[64,96],//ghost facing left coords
    "ratR":[112,144],
    "ratL":[192,128],
    "spiderR":[96,240],
    "spiderL":[112, 240],
    "shopkeepR":[16,128],//no shopkeepL yet
    "gnollR":[224,576],
    "gnollL":[240,576],
    "rangeGoblinR":[80,336],
    "rangeGoblinL":[96,336],
    "mageLichR":[80,160],
    "mageLichL":[64,160]
  }

playerObjects = {
    //separate so user can't place items via place tile?
    //prob start with axe
    "axe":{
        "name":"axe",
        "id":null,
        "holdSprite":{"lt":baseTiles['axeL'], "rt":baseTiles['axeR']},//not all have this
        "itemSprite":baseTiles['axeItem'],//all should have this. only drawn if on ground or inv showing
       // "wear":["hand", true],//all have this, if no wear, set to [null, false]?
    },
    "fishingpole":{
        "name":"fishingpole",
        "id":null,
        "holdSprite":{"lt":baseTiles['fPoleL'], "rt":baseTiles['fPoleR']},
        "itemSprite":baseTiles['fPole']
    },
    "ironsword":{
        "name":"ironsword",
        "id":null,
        "holdSprite":{"lt":baseTiles['ironswordL'], "rt":baseTiles['ironswordR']},
        "itemSprite":baseTiles['ironsword']
    },
    "leatherarmor":{
        "name":"leatherarmor",
        "id":null,
        "holdSprite":{"lt":baseTiles['leatherArmorL'], "rt":baseTiles['leatherArmorR']},//hold? lol
        "itemSprite":baseTiles['leatherArmorI']
    },
    "longbow":{
        "name":"longbow",
        "id":null,
        "holdSprite":{"lt":baseTiles['longbowL'], "rt":baseTiles['longbowR']},
        "itemSprite":baseTiles['longbow']
    },
    "knife":{
        "name":"knife",
        "id":null,
        "holdSprite":{"lt":baseTiles['knifeL'], "rt":baseTiles['knifeR']},
        "itemSprite":baseTiles['knife']
    }
}
  gameObjects = {
    "rangeGoblin":{
        "name":"rangeGoblin",
        "id":null,
        "sprite":{"left":npcTiles['rangeGoblinL'], "right":npcTiles['rangeGoblinR']},
        "facing":"right",
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "mageLich":{
        "name":"mageLich",
        "id":null,
        "sprite":{"left":npcTiles['mageLichL'], "right":npcTiles['mageLichR']},
        "facing":"right",
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "gnoll":{
        "name":"gnoll",
        "id":null,
        "sprite":{"left":npcTiles['gnollL'],"right":npcTiles['gnollR']},
        "facing":"right",
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "spider":{
        "name":"spider",
        "id":null,
        "sprite":{"left":npcTiles['spiderR'],"right":npcTiles['spiderL']},
        "facing":"left",
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "rat":{
        "name":"rat",
        "id":null,
        "sprite":{"left":npcTiles['ratR'],"right":npcTiles['ratL']},
        "facing":"left",
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "shopkeep":{
        "name":"shopkeep",
        "id":null,
        "sprite":npcTiles['shopkeepR'],//{"left":npcTiles['shopkeepR'],"right":npcTiles['shopkeepR']},//remember no left facing for this char yet
        //"facing":"right",
        "type":"object",//another confusing one I know
        "collision":true,
        "attackable":false
    },
    "skeleton":{//character.sprite is now both sets of coords for left and right facing
        "name":"skeleton",//so player/npc sprites get drawn differently
        "id":null,//add id upon npc object creation (if player id added, it will work differently than here)
                  //this way just this object gets put on tile and actual npc object is referenced by id here
        "sprite":{"left":npcTiles['skelR'],"right":npcTiles['skelL']},
        "facing":"left",//players and npcs need this
        "type":"npc",
        "collision":true,
        "attackable":true
    },
    "pebble":{
        "name":"pebble",
        "sprite":baseTiles['pebble'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['pebble']
    },
    "whitewave":{
        "name":"whitewave",
        "sprite":baseTiles['whitewave'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['whitewave']
    },
    "arrow":{
        "name":"arrow",
        "sprite":baseTiles['arrow'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['arrow']
    },
    "fireball":{
        "name":"fireball",
        "sprite":baseTiles['fireball'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fireball']
    },
    "fireballup":{
        "name":"fireballup",
        "sprite":baseTiles['fireballup'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fireballup']
    },
    "fireballdown":{
        "name":"fireballdown",
        "sprite":baseTiles['fireballdown'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fireballdown']
    },
    "fireballleft":{
        "name":"fireballleft",
        "sprite":baseTiles['fireballleft'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fireballleft']
    },
    "fireballright":{
        "name":"fireballright",
        "sprite":baseTiles['fireballright'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fireballright']
    },
    "arrowup":{
        "name":"arrowup",
        "sprite":baseTiles['arrowup'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['arrowup']
    },
    "arrowdown":{
        "name":"arrowdown",
        "sprite":baseTiles['arrowdown'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['arrowdown']
    },
    "arrowleft":{
        "name":"arrowleft",
        "sprite":baseTiles['arrowleft'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['arrowleft']
    },
    "arrowright":{
        "name":"arrowright",
        "sprite":baseTiles['arrowright'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['arrowright']
    },
    "scroll":{
        "name":"scroll",
        "sprite":baseTiles['scroll'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['scroll'],
        "scroll":null,//put what recipe it is (eg "ironsword" or "fishingpole", overlay sprite pulled from baseTiles)
        "ingredients":null//and it's ingredients so player can read recipe, maybe they're a bit cryptic heheh
        //need another way to interact with items to read scroll
    },
    "craftingtable":{
        "name":"craftingtable",
        "id":null,
        "sprite":baseTiles['craftingtable'],
        "type":"object",
        "collision":true,
        "itemSprite":baseTiles['craftingtable']//wait, these necessary for craftingtable/raft etc?
    },
    "raft":{
        "name":"raft",
        "id":null,
        "sprite":baseTiles['raft'],
        "type":"object",
        "collision":true,
        "itemSprite":baseTiles['raft']
    },
    "sail":{
        "name":"sail",
        "sprite":baseTiles['sail'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['sail']
    },
    "apple":{
        "name":"apple",
        "sprite":baseTiles['apple'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['apple']
    },
    "web":{
        "name":"web",
        "sprite":baseTiles['web'],
        "type":"object",
        "collision":false
    },
    "hide":{
        "name":"hide",
        "sprite":baseTiles['hide'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['hide']  
    },
    "brasskey":{
        "name":"brasskey",
        "sprite":baseTiles['brasskey'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['brasskey']
    },
    "key":{
        "name":"key",
        "sprite":baseTiles['key'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['key']
    },
    "coin":{
        "name":"coin",
        "sprite":baseTiles['coin'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['coin']
    },
    "chest2":{
        "name":"chest2",
        "sprite":baseTiles['chest2'],
        "id":null,
        "type":"object",
        "collision":true,
        "itemSprite":baseTiles['chest2']
    },
    "bobber":{
        "name":"bobber",
        "sprite":baseTiles['bobber'],
        "type":"object",
        "collision":false
    },
    "fish":{
        "name":"fish",
        "sprite":baseTiles['fish'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['fish']
    },
    "cookedfish":{
        "name":"cookedfish",
        "sprite":baseTiles['cookedfish'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['cookedfish']
    },
    "tunafish":{
        "name":"tunafish",
        "sprite":baseTiles['tunafish'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['tunafish']
    },
    "cookedtuna":{
        "name":"cookedtuna",
        "sprite":baseTiles['cookedtuna'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['cookedtuna']
    },
    "portalfish":{
        "name":"portalfish",
        "sprite":baseTiles['portalfish'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['portalfish']
    },
    "abyss":{
        "name":"abyss",
        "sprite":baseTiles["abyss"],
        "type":"base-tile",
        "collision":true
    },
    "void":{
        "name":"void",
        "sprite":baseTiles['void'],
        "type":"object",
        "collision":true
    },
    "spikeout":{
        "name":"spikeout",
        "sprite":baseTiles["spikeout"],
        "type":"object",
        "collision":false,
    },
    "spikein":{
        "name":"spikein",
        "sprite":baseTiles["spikein"],
        "type":"object",
        "collision":false
    },
    "lootbag":{
        "name":"lootbag",
        "id":null,
        "sprite":baseTiles["lootbag"],
        "type":"object",
        "collision":true,//so player can interact with it? .action?
        "itemSprite":baseTiles["lootbag"]
    },
    "string":{
        //comes out of a spiders BUTT
        "name":"string",
        "sprite":baseTiles["string"],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles["string"]//maybe if no item sprite just use sprite?
    },
    "log":{
        "name":"log",
        "sprite":baseTiles["log"],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles["log"]//redundant but will work? for inventory drawing ease
    },
    "splitlog":{
        "name":"splitlog",
        "sprite":baseTiles['splitlog'],
        "type":"object",
        "collision":false,
        "itemSprite":baseTiles['splitlog']
    },
    "cloud":{
        "name":"cloud",
        "sprite":baseTiles["cloud"],
        "type":"object",
        "collision":false
    },
    "glasspane1":{
        "name":"glasspane1",
        "sprite":baseTiles["glasspane1"],
        "type":"object",
        "collision":false
    },
    "redDownArrow":{
        "name":"redDownArrow",
        "sprite":baseTiles["redDownArrow"],
        "type":"object",
        "collision":false
    },
    "redX":{
        "name":"redX",
        "sprite":baseTiles["redX"],
        "type":"object",
        "collision":false
    },
    "deskHORIZ":{
        "name":"deskHORIZ",
        "sprite":baseTiles['deskHORIZ'],
        "type":"object",
        "collision":true
    },
    "deskVERT":{
        "name":"deskVERT",
        "sprite":baseTiles['deskVERT'],
        "type":"object",
        "collision":true
    },
    "deskCRV1":{
        "name":"deskCRV1",
        "sprite":baseTiles['deskCRV1'],
        "type":"object",
        "collision":true
    },
    "deskCRV2":{
        "name":"deskCRV2",
        "sprite":baseTiles['deskCRV2'],
        "type":"object",
        "collision":true
    },
    "deskCRV3":{
        "name":"deskCRV3",
        "sprite":baseTiles['deskCRV3'],
        "type":"object",
        "collision":true
    },
    "deskCRV4":{
        "name":"deskCRV4",
        "sprite":baseTiles['deskCRV4'],
        "type":"object",
        "collision":true
    },
    "sign":{
        "name":"sign",
        "id":null,
        "sprite":baseTiles['sign'],
        "type":"object",
        "collision":true,
        "itemSprite":baseTiles['chest2']
    },
    "chair":{
        "name":"chair",
        "sprite":baseTiles['chair'],
        "type":"object",
        "collision":false
    },
    "table":{
        "name":"table",
        "sprite":baseTiles['table'],
        "type":"object",
        "collision":true
    },
    "skull":{
        "name":"skull",
        "sprite":baseTiles['skull'],
        "type":"object",
        "collision":false
    },
    "door":{
        "name":"door",
        "sprite":baseTiles['door'],
        "type":"object",
        "collision":true//change if user try to walk into it and has key?
    },
    "door2":{
        "name":"door2",
        "sprite":baseTiles['door2'],
        "type":"object",
        "collision":true
    },
    "door3":{
        "name":"door3",
        "sprite":baseTiles['door3'],
        "type":"object",
        "collision":true
    },
    "woodplate":{
        "name":"woodplate",
        "sprite":baseTiles['woodplate'],
        "type":"object",
        "collision":false
    },
    "stoneplate":{
        "name":"stoneplate",
        "sprite":baseTiles['stoneplate'],
        "type":"object",
        "collision":false
    },
    "chest":{
        "name":"chest",
        "sprite":baseTiles['chest'],
        "type":"object",
        "collision":true//not sure bout this one
    },
    "ankh":{
        "name":"ankh",
        "sprite":baseTiles['ankh'],
        "type":"object",
        "collision":true
    },
    "cactus":{
        "name":"cactus",
        "sprite":baseTiles['cactus'],
        "type":"object",
        "collision":true
    },
    "bed":{
        "name":"bed",
        "sprite":baseTiles['bed'],
        "type":"object",
        "collision":false
    },
    "dungeonStairs":{
        "name":"dungeonStairs",
        "sprite":baseTiles["dungeonStairs"],
        "type":"object",
        "collision":true,
        "id":null
    },
    "stairsR":{
        "name":"stairsR",
        "sprite":baseTiles['stairsR'],
        "type":"object",
        "collision":true,
        "id":null
    },
    "mapsign":{
        "name":"mapsign",
        "sprite":baseTiles['mapsign'],
        "type":"object",
        "collision":true,
        "id":null
    },
    "rockpile":{
        "name":"rockpile",
        "sprite":baseTiles['rockpile'],
        "type":"object",
        "collision":true
    },
    "boulder":{
        "name":"boulder",
        "sprite":baseTiles['boulder'],
        "type":"object",
        "collision":true
    },
    "sand":{
        "name":"sand",
        "sprite":baseTiles['sand'],
        "type":"base-tile",
        "collision":false
    },
    "fenceV":{
        "name":"fenceV",
        "sprite":baseTiles['fenceV'],
        "type":"object",
        "collision":true
    },
    "fenceH":{
        "name":"fenceH",
        "sprite":baseTiles['fenceH'],
        "type":"object",
        "collision":true
    },
    "grass2":{
        "name":"grass2",
        "sprite":baseTiles['grass2'],
        "type":"object",
        "collision":false
    },
    "rain":{//this is also the speedboot trail sprite
        "name":"rain",
        "sprite":baseTiles['rain'],
        "type":"object",
        "collision":false,
    },
    "stump3":{
        "name":"stump3",
        "sprite":baseTiles['stump3'],
        "type":"object",
        "collision":true,
    },
    "stump2":{
        "name":"stump2",
        "sprite":baseTiles['stump2'],
        "type":"object",
        "collision":true,
    },
    "stump1":{
        "name":"stump1",
        "sprite":baseTiles['stump1'],
        "type":"object",
        "collision":false,
    },
    "trashcan":{
        "name":"trashcan",
        "sprite":baseTiles['trashcan'],
        "type":"object",
        "collision":true
    },
    "campfire":{
        "name":"campfire",
        "sprite":baseTiles['campfire'],
        "type":"object",
        "collision":true,
    },
    "grave":{
        "name":"grave",
        "sprite":baseTiles['grave'],
        "type":"object",
        "collision":true,
    },
    "stoneblock":{
        "name":"stoneblock",
        "sprite":baseTiles['stoneblock'],
        "type":"object",
        "collision":true,
    },
    "woodblock":{
        "name":"woodblock",
        "sprite":baseTiles['woodblock'],
        "type":"object",
        "collision":true,
    },
    "rock":{
        "name":"rock",//won't be any issues with this? will probably need id and stuff eventually
        "sprite":baseTiles['rock'],//object['sprite'][0]/[1] are sprite coords
        "type":"base-tile",//as opposed to player or base-tile
        "collision":true,
    },
    "grass":{
        "name":"grass",
        "sprite":baseTiles['grass'],
        "type":"base-tile",//as opposed to object or player
        "collision":false,
    },
    "tree":{
        "name":"tree",
        "sprite":baseTiles['tree'],//need to account for a chopped up tree (same obj, change sprite?)
        "type":"object",//as opposed to object or player
        "collision":true,
    },
    "palmtree":{
        "name":"palmtree",
        "sprite":baseTiles['palmtree'],
        "type":"object",
        "collision":true
    },
    "water":{
        "name":"water",
        "sprite":baseTiles['water'],
        "type":"base-tile",
        "collision":true,
    },
    "oak":{
        "name":"oak",
        "sprite":baseTiles['oak'],
        "type":"object",
        "collision":true,
    },
    "snow":{
        "name":"snow",
        "sprite":baseTiles['snow'],
        "type":"base-tile",
        "collision":false,
    },
    "mushroom":{
        "name":"mushroom",
        "sprite":baseTiles['mushroom'],
        "type":"object",
        "collision":true,
    },
    "deadtree":{
        "name":"deadtree",
        "sprite":baseTiles['deadtree'],
        "type":"object",
        "collision":true,
    },
    "snowtree":{
        "name":"snowtree",
        "sprite":baseTiles['snowtree'],
        "type":"object",
        "collision":true,
    },
    "flower1":{
        "name":"flower1",
        "sprite":baseTiles['flower1'],
        "type":"object",
        "collision":false,
    },
    "flower2":{
        "name":"flower2",
        "sprite":baseTiles['flower2'],
        "type":"object",
        "collision":false,
    },
    "flower3":{
        "name":"flower3",
        "sprite":baseTiles['flower3'],
        "type":"object",
        "collision":false,
    },
    "pathHORIZ":{
        "name":"pathHORIZ",
        "sprite":baseTiles['pathHORIZ'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathVERT":{
        "name":"pathVERT",
        "sprite":baseTiles['pathVERT'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathTDWN":{
        "name":"pathTDWN",
        "sprite":baseTiles['pathTDWN'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathTUP":{
        "name":"pathTUP",
        "sprite":baseTiles['pathTUP'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathTRT":{
        "name":"pathTRT",
        "sprite":baseTiles['pathTRT'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathTLT":{
        "name":"pathTLT",
        "sprite":baseTiles['pathTLT'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathCRS":{
        "name":"pathCRS",
        "sprite":baseTiles['pathCRS'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathCRV1":{
        "name":"pathCRV1",
        "sprite":baseTiles['pathCRV1'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathCRV2":{
        "name":"pathCRV2",
        "sprite":baseTiles['pathCRV2'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathCRV3":{
        "name":"pathCRV3",
        "sprite":baseTiles['pathCRV3'],
        "type":"object",
        "collision":false,
        "coll_override":true
    },
    "pathCRV4":{
        "name":"pathCRV4",
        "sprite":baseTiles['pathCRV4'],
        "type":"object",
        "collision":false,
        "coll_override":true
    }
}
